name: quicksnap2pdf
description: "Quickly convert PNGs & JPEGs to a PDF file with no limit."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.14.2
  desktop_drop: ^0.6.0
  open_file: ^3.5.10
  pdf: ^3.11.3
  path_provider: ^2.1.5
  fluent_ui: ^4.11.3
  system_theme: ^3.1.2
  file_selector: 1.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
